root /var/www/html/public;
index index.php index.html;

# ??? ?????? ??????? ??????? (.env ...)
location ~ /\. { deny all; }

location / {
    try_files \ \/ /index.php?\;
}

location ~ \.php\$ {
    include       fastcgi_params;
    fastcgi_param SCRIPT_FILENAME \\;
    fastcgi_param DOCUMENT_ROOT   \;
    fastcgi_pass  unix:/run/php-fpm/www.sock;
    fastcgi_index index.php;
}
